# Generated by Django 2.2 on 2020-08-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
