# Generated by Django 2.2 on 2020-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0002_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='https://i.ibb.co/FbSVkhk/Default.png', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
