# Generated by Django 2.2 on 2020-08-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0002_auto_20200801_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
    ]
